// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlHIpB5cigryoPknfOXc4ZxSmeMy2XUkM',
    appId: '1:36597009887:web:ec70ce4c91ed441c53486a',
    messagingSenderId: '36597009887',
    projectId: 'college-finder-54f2c',
    authDomain: 'college-finder-54f2c.firebaseapp.com',
    storageBucket: 'college-finder-54f2c.appspot.com',
    measurementId: 'G-5HMR6JQ6YV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwlXZjDodx4lvfLnak8Hp7aMJb25I9z_o',
    appId: '1:36597009887:android:e97af98db4a0597b53486a',
    messagingSenderId: '36597009887',
    projectId: 'college-finder-54f2c',
    storageBucket: 'college-finder-54f2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3k33Dg7GCpM4rTktKBPLdVc709rYx5qw',
    appId: '1:36597009887:ios:5f301596657efff153486a',
    messagingSenderId: '36597009887',
    projectId: 'college-finder-54f2c',
    storageBucket: 'college-finder-54f2c.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3k33Dg7GCpM4rTktKBPLdVc709rYx5qw',
    appId: '1:36597009887:ios:499333b7bd084be353486a',
    messagingSenderId: '36597009887',
    projectId: 'college-finder-54f2c',
    storageBucket: 'college-finder-54f2c.appspot.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
