// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwlXZjDodx4lvfLnak8Hp7aMJb25I9z_o',
    appId: '1:36597009887:web:ec70ce4c91ed441c53486a',
    messagingSenderId: '36597009887',
    projectId: 'college-finder-54f2c',
    authDomain: 'college-finder-54f2c.firebaseapp.com',
    storageBucket: 'college-finder-54f2c.appspot.com',
    measurementId: 'G-5HMR6JQ6YV', // Retained from your original code if still applicable
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwlXZjDodx4lvfLnak8Hp7aMJb25I9z_o',
    appId: '1:36597009887:android:0fec54d9bc8e280453486a',
    messagingSenderId: '36597009887',
    projectId: 'college-finder-54f2c',
    storageBucket: 'college-finder-54f2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwlXZjDodx4lvfLnak8Hp7aMJb25I9z_o',
    appId: '1:36597009887:ios:5f301596657efff153486a', // Adjust if there's an updated appId for iOS
    messagingSenderId: '36597009887',
    projectId: 'college-finder-54f2c',
    storageBucket: 'college-finder-54f2c.appspot.com',
    iosBundleId: 'com.frugal', // Updated from the google-services.json file
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwlXZjDodx4lvfLnak8Hp7aMJb25I9z_o',
    appId: '1:36597009887:ios:499333b7bd084be353486a', // Retained from your original code if still applicable
    messagingSenderId: '36597009887',
    projectId: 'college-finder-54f2c',
    storageBucket: 'college-finder-54f2c.appspot.com',
    iosBundleId: 'com.frugal.RunnerTests', // Adjusted based on your app setup if necessary
  );
}
