default_platform(:android)
lane :increment_build_num do
  app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
  previous_build_number = google_play_track_version_codes(
    package_name: app_identifier,
    track: "internal",
    json_key: ENV["ANDROID_JSON_KEY_FILE"]
  )[0]

  current_build_number = previous_build_number + 1

  increment_version_code(
    gradle_file_path: "android/app/build.gradle",
    version_code: current_build_number
  )
end