default_platform(:android)

lane :increment_build_num do
    previous_build_number = google_play_track_version_codes(
      package_name: 'com.frugal.CollegeFinder',
      track: "internal",
      json_key: "./app/key.json",
    )[0]

    current_build_number = previous_build_number + 1

    increment_version_code(
      gradle_file_path: "./app/build.gradle",
      version_code: current_build_number
    )
 end
