default_platform(:android)

lane :increment_build_num do
  # Read Google API JSON key from the environment variable
  google_service_account_key = ENV["GOOGLE_SERVICE_ACCOUNT_KEY"]
  
  # Define JSON key file path
  json_key_path = "./app/key.json"

  # Write the key contents to a file
  File.open(json_key_path, "w") { |file| file.write(google_service_account_key) }

  # Get previous build number from Google Play Console
  previous_build_number = google_play_track_version_codes(
    package_name: 'com.frugal.CollegeFinder',
    track: "internal",
    json_key: json_key_path
  )[0]

  current_build_number = previous_build_number + 1

  # Update versionCode in build.gradle
  sh "sed -i 's/versionCode [0-9]\\+/versionCode #{current_build_number}/' ./app/build.gradle"
end
